name: Publish ASV Dashboard

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-benchmarks:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install ASV
        run: pip install asv

      - name: Set up git user
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Publish last month of results
        run: asv publish '--since="1 month ago" main'

      # Need to generate manually to work with the command above
      - name: Deploy to gh-pages
        run: |
          mv html /tmp/asv-html
          git fetch origin gh-pages:gh-pages || true
          git checkout --orphan gh-pages-tmp
          git rm -rf .
          rm -rf newton env html results .github
          cp -r /tmp/asv-html/* .
          touch .nojekyll
          git add -A
          git commit -m "Generated from sources"
          git push origin HEAD:gh-pages --force
